seeder:
    file: ./seeder/seeder.rb
    disabled: false
  
parsers:
  - file: ./parsers/listings.rb
    page_type: listings
    disabled: false

  - file: ./parsers/product.rb
    page_type: product
    disabled: false