exporter_name: products_csv
exporter_type: csv
collection: products
start_on_job_done: true
fields:
 - header: "gid" 
   path: "_gid"
 - header: "created_at" 
   path: "_created_at"
 - header: "category" 
   path: "category"
 - header: "discount_price" 
   path: "discount_price"
 - header: "image_url" 
   path: "image_url"
 - header: "order" 
   path: "order"
 - header: "rating" 
   path: "rating"
 - header: "reviews_count" 
   path: "reviews_count"
 - header: "title" 
   path: "title"
 - header: "url" 
   path: "url"